// place files you want to import through the `$lib` alias in this folder.
export const items = {
	'1-1': "McDonald's",
	'1-2': "Dunkin' Donuts",
	'1-3': 'Burger King',
	'1-4': 'Taco Bell',
	'1-5': "Wendy's",
	'1-6': 'Dairy Queen',
	'1-7': 'Little Caesars',
	'1-8': 'KFC',
	'1-9': 'Sonic',
	'1-10': "Arby's",
	'1-11': 'Chipotle',
	'1-12': "Jimmy John's",
	'1-13': 'Chick-fil-A',
	'1-14': 'Panda Express',
	'1-15': 'Jack in the Box',
	'1-16': 'Panera Bread',
	'1-17': 'Jersey Mike',
	'1-18': 'Five Guys',
	'1-19': 'Firehouse Subs',
	'1-20': 'Zaxby',
	'1-21': "Checkers and Rally's",
	'1-22': "Culver's",
	'1-23': 'Bojangles',
	'1-24': "Steak 'n Shake",
	'1-25': "Freddy's Frozen Custard & Steakburgers",
	'1-26': 'Quiznos',
	'2-1': 'Noodles & Company',
	'2-2': 'Einstein Bros. Bagels',
	'2-3': 'Jamba Juice',
	'2-4': "Applebee's",
	'2-5': 'The Cheesecake Factory',
	'2-6': 'Golden Corral',
	'2-7': "Denny's",
	'2-8': 'IHOP',
	'2-9': 'Waffle House',
	'2-10': "Chili's",
	'2-11': 'Olive Garden',
	'2-12': 'Cracker Barrel',
	'2-13': "Dickey's Barbecue Pit",
	'2-14': 'Texas Roadhouse / Longhorn Steakhouse'
};
